openapi: 3.0.2
info:
  title: GIS Demo
  description: A demo of a GIS application
  version: 0.1.0
paths:
  /geojson/municipalities.geojson:
    get:
      operationId: listMunicipalityFeatures
      responses:
        200:
          description: Municipalities of Norway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MunicipalityFeatureCollection'
  /geojson/schools.geojson:
    get:
      operationId: listSchoolFeatures
      responses:
        200:
          description: Schools
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolFeatureCollection'
components:
  schemas:
    MunicipalityFeatureCollection:
      allOf:
        - $ref: "./schema/geojson.yaml#/FeatureCollection"
        - properties:
            features:
              type: array
              items:
                $ref: "#/components/schemas/MunicipalityFeature"
          required:
            - features
    MunicipalityFeature:
      allOf:
        - $ref: "./schema/geojson.yaml#/Feature"
        - properties:
            geometry:
              $ref: "./schema/geojson.yaml#/Polygon"
            properties:
              $ref: "#/components/schemas/MunicipalityFeatureProperties"
          required:
            - properties
    MunicipalityFeatureProperties:
      properties:
        kommunenummer:
          type: string
        navn:
          type: string
      required:
        - kommunenummer
        - navn
    SchoolFeatureCollection:
      allOf:
        - $ref: "./schema/geojson.yaml#/FeatureCollection"
        - properties:
            features:
              type: array
              items:
                $ref: "#/components/schemas/SchoolFeature"
          required:
            - features
    SchoolFeature:
      allOf:
        - $ref: "./schema/geojson.yaml#/Feature"
        - properties:
            geometry:
              $ref: "./schema/geojson.yaml#/Point"
            properties:
              $ref: "#/components/schemas/SchoolFeatureProperties"
          required:
            - properties
    SchoolFeatureProperties:
      properties:
        navn:
          type: string
        antall_elever:
          type: integer
          format: int32
        antall_ansatte:
          type: integer
          format: int32
        eierforhold:
          type: string
          enum:
            - Offentlig
            - Privat
        kommunenummer:
          type: string
          format: numeric
      required:
        - navn
        - antall_ansatte
        - antall_elever
        - eierforhold
        - kommunenummer